[package]
name = "protoc-grpcio"
version = "0.1.1"
authors = ["Matt Pelland <matt@pelland.io>"]
license = "Apache-2.0"
keywords = ["compiler", "grpc", "protobuf", "grpc-rs"]
repository = "https://github.com/mtp401/protoc-grpcio"
documentation = "https://docs.rs/protoc-grpcio"
description = """
API for programatically invoking the grpcio (grpc-rs) gRPC compiler"
"""

[dependencies]
grpcio-compiler = "0.2"
failure = "0.1"
mktemp = "0.3"
protobuf = "1.4"
protoc = "1.4"